import FormalConjectures.ErdosProblems.«1004»
import TaskSupport

open Filter Real Nat

namespace Contribution.Erdos1004PrimePair

/-- `IsMinusPrimePair p` records the prime-pair pattern `p, 2p - 1`, excluding
its exceptional value `p = 2`.  Such a pair supplies a totient collision at
`4p - 2` and `4p`. -/
def IsMinusPrimePair (p : ℕ) : Prop :=
  3 ≤ p ∧ p.Prime ∧ (2 * p - 1).Prime

/-- A collision between two distinct points of the run interval rules out
`Erdos1004.IsDistinctTotientRun`. -/
theorem not_isDistinctTotientRun_of_collision
    {n K a b : ℕ}
    (ha : a ∈ Set.Icc (n + 1) (n + K))
    (hb : b ∈ Set.Icc (n + 1) (n + K))
    (hab : a ≠ b)
    (hφ : Nat.totient a = Nat.totient b) :
    ¬ Erdos1004.IsDistinctTotientRun n K := by
  intro hrun
  exact hab (hrun ha hb hφ)

/-- Multiplying two prime suppliers by coprime coefficients turns an equality
of the corresponding Euler factors into an equality of totients.  This is a
small reusable interface for structured Graham--Holt--Pomerance collisions. -/
theorem totient_mul_prime_eq_totient_mul_prime
    {a b p q : ℕ}
    (hp : p.Prime) (hq : q.Prime)
    (hap : a.Coprime p) (hbq : b.Coprime q)
    (hfactor : Nat.totient a * (p - 1) = Nat.totient b * (q - 1)) :
    Nat.totient (a * p) = Nat.totient (b * q) := by
  rw [Nat.totient_mul hap, Nat.totient_mul hbq,
    Nat.totient_prime hp, Nat.totient_prime hq]
  exact hfactor

/-- The elementary prime-pair family gives the exact collision
`φ(4p - 2) = φ(4p)`. -/
theorem totient_four_mul_sub_two_eq_totient_four_mul
    {p : ℕ} (hp : IsMinusPrimePair p) :
    Nat.totient (4 * p - 2) = Nat.totient (4 * p) := by
  rcases hp with ⟨hp3, hpprime, hqprime⟩
  have hpne : p ≠ 2 := by omega
  have hqne : 2 * p - 1 ≠ 2 := by omega
  have hpodd : Odd p := hpprime.odd_of_ne_two hpne
  have hqodd : Odd (2 * p - 1) := hqprime.odd_of_ne_two hqne
  have hcop2q : Nat.Coprime 2 (2 * p - 1) := Nat.coprime_two_left.mpr hqodd
  have hcop2p : Nat.Coprime 2 p := Nat.coprime_two_left.mpr hpodd
  have hcop4p : Nat.Coprime 4 p := by
    simpa using Nat.Coprime.pow_left 2 hcop2p
  have hφ4 : Nat.totient 4 = 2 := by norm_num [Nat.totient]
  calc
    Nat.totient (4 * p - 2) = Nat.totient (2 * (2 * p - 1)) := by
      congr 1 <;> omega
    _ = Nat.totient 2 * Nat.totient (2 * p - 1) := Nat.totient_mul hcop2q
    _ = 2 * p - 2 := by
      rw [Nat.totient_two, Nat.totient_prime hqprime]
      omega
    _ = Nat.totient 4 * Nat.totient p := by
      rw [hφ4, Nat.totient_prime hpprime]
      omega
    _ = Nat.totient (4 * p) := (Nat.totient_mul hcop4p).symm

/-- If a candidate run contains both endpoints generated by a minus prime pair,
then the run is not totient-distinct. -/
theorem not_isDistinctTotientRun_of_minusPrimePair
    {n K p : ℕ} (hp : IsMinusPrimePair p)
    (hleft : n + 1 ≤ 4 * p - 2)
    (hright : 4 * p ≤ n + K) :
    ¬ Erdos1004.IsDistinctTotientRun n K := by
  apply not_isDistinctTotientRun_of_collision
      (a := 4 * p - 2) (b := 4 * p)
  · exact ⟨hleft, by omega⟩
  · exact ⟨by omega, hright⟩
  · have hp3 := hp.1
    omega
  · exact totient_four_mul_sub_two_eq_totient_four_mul hp

/-- Equivalently, every totient-distinct run avoids at least one endpoint of
each prime-pair collision. -/
theorem isDistinctTotientRun_avoids_minusPrimePair
    {n K p : ℕ} (hrun : Erdos1004.IsDistinctTotientRun n K)
    (hp : IsMinusPrimePair p) :
    4 * p - 2 < n + 1 ∨ n + K < 4 * p := by
  by_cases hleft : n + 1 ≤ 4 * p - 2
  · right
    by_contra hright
    exact (not_isDistinctTotientRun_of_minusPrimePair hp hleft
      (Nat.le_of_not_gt hright)) hrun
  · left
    exact Nat.lt_of_not_ge hleft

/-- A local coverage hypothesis immediately rules out a candidate run.  This
is the point at which analytic information about gaps between the prime pairs
can be plugged into the formal target. -/
theorem not_isDistinctTotientRun_of_minusPrimePair_coverage
    {n K : ℕ}
    (hcover : ∃ p, IsMinusPrimePair p ∧
      n + 1 ≤ 4 * p - 2 ∧ 4 * p ≤ n + K) :
    ¬ Erdos1004.IsDistinctTotientRun n K := by
  rcases hcover with ⟨p, hp, hleft, hright⟩
  exact not_isDistinctTotientRun_of_minusPrimePair hp hleft hright

/-- Eventual prime-pair coverage for a length function `L` gives eventual
failure of every run with start at most `x`. -/
theorem eventually_no_distinct_run_of_minusPrimePair_coverage
    {L : ℕ → ℕ}
    (hcover : ∀ᶠ x : ℕ in atTop, ∀ n ≤ x, ∃ p,
      IsMinusPrimePair p ∧ n + 1 ≤ 4 * p - 2 ∧ 4 * p ≤ n + L x) :
    ∀ᶠ x : ℕ in atTop, ∀ n ≤ x,
      ¬ Erdos1004.IsDistinctTotientRun n (L x) := by
  filter_upwards [hcover] with x hx
  intro n hn
  exact not_isDistinctTotientRun_of_minusPrimePair_coverage (hx n hn)

/-- Target-facing conditional refutation.  To refute Erdős 1004 it is enough
to prove, for one positive exponent, that every sufficiently large candidate
window contains one of the prime-pair collisions above.  The theorem packages
all remaining work as the displayed analytic coverage hypothesis. -/
theorem not_target_of_eventual_minusPrimePair_coverage
    {c : ℝ} (hc : 0 < c)
    (hcover : ∀ᶠ x : ℕ in atTop, ∀ n ≤ x, ∃ p,
      IsMinusPrimePair p ∧
        n + 1 ≤ 4 * p - 2 ∧
        4 * p ≤ n + ⌊(Real.log (x : ℝ)) ^ c⌋₊) :
    ¬ (fcTypeOfName% "Erdos1004.erdos_1004") := by
  intro htarget
  have hpositive :
      ∀ d > (0 : ℝ), ∀ᶠ x : ℕ in atTop, ∃ n ≤ x,
        Erdos1004.IsDistinctTotientRun n ⌊(Real.log (x : ℝ)) ^ d⌋₊ :=
    htarget.mp trivial
  obtain ⟨Xrun, hXrun⟩ := eventually_atTop.1 (hpositive c hc)
  obtain ⟨Xcover, hXcover⟩ := eventually_atTop.1 hcover
  let x := max Xrun Xcover
  obtain ⟨n, hn, hrun⟩ := hXrun x (le_max_left Xrun Xcover)
  obtain ⟨p, hp, hleft, hright⟩ :=
    hXcover x (le_max_right Xrun Xcover) n hn
  exact (not_isDistinctTotientRun_of_minusPrimePair hp hleft hright) hrun

/-- A concrete checked use of the collision API: the run on `[9,12]` fails
because `φ(10) = φ(12)`. -/
theorem not_isDistinctTotientRun_eight_four :
    ¬ Erdos1004.IsDistinctTotientRun 8 4 := by
  apply not_isDistinctTotientRun_of_minusPrimePair (p := 3)
  · norm_num [IsMinusPrimePair, Nat.prime_def]
  · norm_num
  · norm_num

end Contribution.Erdos1004PrimePair
