import FormalConjectures.ErdosProblems.«1004»

open Filter Real Nat

namespace Contribution.Erdos1004PrimePair

/-- The positive assertion on the right-hand side of the normalized Erdős 1004
reward target. Naming it makes the target-facing consequences below reusable
without depending on the validator's `fcTypeOfName%` elaborator. -/
def Erdos1004Assertion : Prop :=
  ∀ c > (0 : ℝ), ∀ᶠ x : ℕ in atTop, ∃ n ≤ x,
    Erdos1004.IsDistinctTotientRun n ⌊(Real.log (x : ℝ)) ^ c⌋₊

/-- `IsMinusPrimePair p` records the prime-pair pattern `p, 2p - 1`, excluding
its exceptional value `p = 2`. Such a pair supplies a totient collision at
`4p - 2` and `4p`. -/
def IsMinusPrimePair (p : ℕ) : Prop :=
  3 ≤ p ∧ p.Prime ∧ (2 * p - 1).Prime

/-- The collision generated by `p` lies completely inside the candidate run
`[n + 1, n + K]`. -/
def MinusPrimePairCovers (n K p : ℕ) : Prop :=
  IsMinusPrimePair p ∧ n + 1 ≤ 4 * p - 2 ∧ 4 * p ≤ n + K

/-- A collision between two distinct points of the run interval rules out
`Erdos1004.IsDistinctTotientRun`. -/
theorem not_isDistinctTotientRun_of_collision
    {n K a b : ℕ}
    (ha : a ∈ Set.Icc (n + 1) (n + K))
    (hb : b ∈ Set.Icc (n + 1) (n + K))
    (hab : a ≠ b)
    (hφ : Nat.totient a = Nat.totient b) :
    ¬ Erdos1004.IsDistinctTotientRun n K := by
  intro hrun
  exact hab (hrun ha hb hφ)

/-- Multiplying two prime suppliers by coprime coefficients turns an equality
of their Euler factors into an equality of totients. This is a reusable kernel
for structured Graham--Holt--Pomerance collision constructions. -/
theorem totient_mul_prime_eq_totient_mul_prime
    {a b p q : ℕ}
    (hp : p.Prime) (hq : q.Prime)
    (hap : a.Coprime p) (hbq : b.Coprime q)
    (hfactor : Nat.totient a * (p - 1) = Nat.totient b * (q - 1)) :
    Nat.totient (a * p) = Nat.totient (b * q) := by
  rw [Nat.totient_mul hap, Nat.totient_mul hbq,
    Nat.totient_prime hp, Nat.totient_prime hq]
  exact hfactor

/-- The elementary Moser--Schinzel prime-pair family gives the exact collision
`φ(4p - 2) = φ(4p)`. -/
theorem totient_four_mul_sub_two_eq_totient_four_mul
    {p : ℕ} (hp : IsMinusPrimePair p) :
    Nat.totient (4 * p - 2) = Nat.totient (4 * p) := by
  rcases hp with ⟨hp3, hpprime, hqprime⟩
  have hpne : p ≠ 2 := by omega
  have hqne : 2 * p - 1 ≠ 2 := by omega
  have hpodd : Odd p := hpprime.odd_of_ne_two hpne
  have hqodd : Odd (2 * p - 1) := hqprime.odd_of_ne_two hqne
  have hcop2q : Nat.Coprime 2 (2 * p - 1) := Nat.coprime_two_left.mpr hqodd
  have hcop2p : Nat.Coprime 2 p := Nat.coprime_two_left.mpr hpodd
  have hcop4p : Nat.Coprime 4 p := by
    simpa using hcop2p.pow_left 2
  have hφ4 : Nat.totient 4 = 2 := by norm_num [Nat.totient]
  have hfactor :
      Nat.totient 2 * ((2 * p - 1) - 1) =
        Nat.totient 4 * (p - 1) := by
    rw [Nat.totient_two, hφ4]
    omega
  have hcollision := totient_mul_prime_eq_totient_mul_prime
    hqprime hpprime hcop2q hcop4p hfactor
  convert hcollision using 1 <;> omega

/-- If a candidate run contains both endpoints generated by a minus prime pair,
then the run is not totient-distinct. -/
theorem not_isDistinctTotientRun_of_minusPrimePair
    {n K p : ℕ} (hp : IsMinusPrimePair p)
    (hleft : n + 1 ≤ 4 * p - 2)
    (hright : 4 * p ≤ n + K) :
    ¬ Erdos1004.IsDistinctTotientRun n K := by
  apply not_isDistinctTotientRun_of_collision
      (a := 4 * p - 2) (b := 4 * p)
  · exact ⟨hleft, by omega⟩
  · exact ⟨by omega, hright⟩
  · have hp3 := hp.1
    omega
  · exact totient_four_mul_sub_two_eq_totient_four_mul hp

/-- The bundled coverage predicate is a direct certificate that a candidate
run fails. -/
theorem not_isDistinctTotientRun_of_minusPrimePairCovers
    {n K p : ℕ} (hcover : MinusPrimePairCovers n K p) :
    ¬ Erdos1004.IsDistinctTotientRun n K := by
  exact not_isDistinctTotientRun_of_minusPrimePair
    hcover.1 hcover.2.1 hcover.2.2

/-- Every totient-distinct run avoids at least one endpoint of each supplied
prime-pair collision. This is the exact finite gap obligation imposed on the
prime-pair sequence by Erdős 1004. -/
theorem isDistinctTotientRun_avoids_minusPrimePair
    {n K p : ℕ} (hrun : Erdos1004.IsDistinctTotientRun n K)
    (hp : IsMinusPrimePair p) :
    4 * p - 2 < n + 1 ∨ n + K < 4 * p := by
  by_cases hleft : n + 1 ≤ 4 * p - 2
  · right
    by_contra hright
    exact (not_isDistinctTotientRun_of_minusPrimePair hp hleft
      (Nat.le_of_not_gt hright)) hrun
  · left
    exact Nat.lt_of_not_ge hleft

/-- A candidate run is disjoint from the complete-coverage certificates
provided by the minus prime-pair family. -/
theorem isDistinctTotientRun_not_minusPrimePairCovers
    {n K p : ℕ} (hrun : Erdos1004.IsDistinctTotientRun n K) :
    ¬ MinusPrimePairCovers n K p := by
  intro hcover
  exact (not_isDistinctTotientRun_of_minusPrimePairCovers hcover) hrun

/-- The positive Erdős 1004 assertion forces eventual candidate runs which
avoid every collision from the minus prime-pair family. This exposes a concrete
prime-gap consequence of any future proof of the target. -/
theorem assertion_implies_eventually_minusPrimePair_free_run
    (hassertion : Erdos1004Assertion) {c : ℝ} (hc : 0 < c) :
    ∀ᶠ x : ℕ in atTop, ∃ n ≤ x, ∀ p,
      ¬ MinusPrimePairCovers n ⌊(Real.log (x : ℝ)) ^ c⌋₊ p := by
  filter_upwards [hassertion c hc] with x hx
  rcases hx with ⟨n, hn, hrun⟩
  exact ⟨n, hn, fun p => isDistinctTotientRun_not_minusPrimePairCovers hrun⟩

/-- Eventual prime-pair coverage for a length function `L` gives eventual
failure of every run with start at most `x`. -/
theorem eventually_no_distinct_run_of_minusPrimePair_coverage
    {L : ℕ → ℕ}
    (hcover : ∀ᶠ x : ℕ in atTop, ∀ n ≤ x, ∃ p,
      MinusPrimePairCovers n (L x) p) :
    ∀ᶠ x : ℕ in atTop, ∀ n ≤ x,
      ¬ Erdos1004.IsDistinctTotientRun n (L x) := by
  filter_upwards [hcover] with x hx
  intro n hn
  obtain ⟨p, hp⟩ := hx n hn
  exact not_isDistinctTotientRun_of_minusPrimePairCovers hp

/-- For one positive exponent, eventual coverage of every candidate window by
these checked collisions contradicts the assertion on the right-hand side of
Erdős 1004. All remaining mathematical work is isolated in `hcover`. -/
theorem not_assertion_of_eventual_minusPrimePair_coverage
    {c : ℝ} (hc : 0 < c)
    (hcover : ∀ᶠ x : ℕ in atTop, ∀ n ≤ x, ∃ p,
      MinusPrimePairCovers n ⌊(Real.log (x : ℝ)) ^ c⌋₊ p) :
    ¬ Erdos1004Assertion := by
  intro hassertion
  obtain ⟨Xrun, hXrun⟩ := eventually_atTop.1 (hassertion c hc)
  obtain ⟨Xcover, hXcover⟩ := eventually_atTop.1 hcover
  let x := max Xrun Xcover
  obtain ⟨n, hn, hrun⟩ := hXrun x (le_max_left Xrun Xcover)
  obtain ⟨p, hp⟩ := hXcover x (le_max_right Xrun Xcover) n hn
  exact (not_isDistinctTotientRun_of_minusPrimePairCovers hp) hrun

/-- Conditional refutation of the normalized reward-target type
`True ↔ Erdos1004Assertion`. This is the target-facing handoff: an analytic
coverage theorem with the displayed shape can be plugged in directly. -/
theorem not_normalized_target_of_eventual_minusPrimePair_coverage
    {c : ℝ} (hc : 0 < c)
    (hcover : ∀ᶠ x : ℕ in atTop, ∀ n ≤ x, ∃ p,
      MinusPrimePairCovers n ⌊(Real.log (x : ℝ)) ^ c⌋₊ p) :
    ¬ (True ↔ Erdos1004Assertion) := by
  intro htarget
  exact (not_assertion_of_eventual_minusPrimePair_coverage hc hcover)
    (htarget.mp trivial)

/-- A concrete checked use of the collision API: the run on `[9, 12]` fails
because the prime pair `3, 5` supplies `φ(10) = φ(12)`. -/
theorem not_isDistinctTotientRun_eight_four :
    ¬ Erdos1004.IsDistinctTotientRun 8 4 := by
  apply not_isDistinctTotientRun_of_minusPrimePair (p := 3)
  · norm_num [IsMinusPrimePair, Nat.prime_def]
  · norm_num
  · norm_num

end Contribution.Erdos1004PrimePair
